#!/usr/bin/env python3
"""Verificación independiente de un .docx corregido.

Uso: python verificar_docx.py ARCHIVO.docx [--revisor "Prof. Nombre"] [--sin-persona] [--json]
Comprueba: patrones prohibidos (con contexto, porque hay falsos positivos), campo PAGE en el pie, datos mínimos de portada
(materia, unidad, tema y revisor, con cualquier rótulo parecido), metadatos del archivo y, solo como dato informativo,
cuántas referencias bibliográficas detecta.
--sin-persona: no cuenta segunda persona, primera persona ni futuros (para cuando CRITERIOS.md fija otro estilo de redacción).
NUNCA reemplaza la lectura completa ni la revisión manual del tutor: es un control mecánico.
"""
import json
import re
import sys
import zipfile

PATRONES = {
    "segunda_persona": r"\b(tú|vos|tu|tus|puedes|podés|considera|usa|uses|imagina|recuerda|recordá|fíjate|fijate|avisame|aquí tienes)\b",
    "primera_persona": r"\b(vamos|veremos|nuestr[oa]s?|hemos|aprendimos|esperamos|agregamos|vimos)\b",
    "futuro": r"\b\w{4,}(ará|arán|erá|erán|irá|irán)\b",
    "markdown": r"(\*\*|##|```)",
    "guion_largo_en_oracion": r"\S — \S",
    "emoji": "[\U0001F300-\U0001FAFF☀-➿]",
    "relleno_ia": r"(Es importante destacar|Claro, aqu|Por supuesto|Espero que|En resumen,|En conclusión,|Como modelo de lenguaje)",
    "marcador_plantilla": r"(\[Nombre|\[nombre|<completar>|(?-i:\bTODO\b)|Lorem ipsum)",
}
# Patrones que dependen del estilo de redacción elegido (por defecto, tercera persona impersonal)
PATRONES_DE_ESTILO = ("segunda_persona", "primera_persona", "futuro")
# Rótulos aceptados para los datos mínimos de portada (el archivo puede usar otros nombres)
ROTULOS_PORTADA = {
    "materia": r"(materia|asignatura|curso)",
    "unidad": r"unidad",
    "tema": r"(tema|t[ií]tulo)",
    "revisor": r"(revisor|auditor|revisado por)",
}
# Palabras que suelen ser falsos positivos: se muestran con contexto para que se lean antes de reportar.
AMBIGUAS = {"usa", "uses", "considera", "tu"}


def texto_docx(z):
    x = z.read("word/document.xml").decode("utf8")
    x = re.sub(r"</w:p>", "\n", x)
    return re.sub(r"[ \t]+", " ", re.sub(r"<[^>]+>", " ", x))


def main():
    if len(sys.argv) < 2:
        print(__doc__); return 2
    ruta = sys.argv[1]
    revisor = sys.argv[sys.argv.index("--revisor") + 1] if "--revisor" in sys.argv else None
    z = zipfile.ZipFile(ruta)
    t = texto_docx(z)
    plano = re.sub(r"\s+", " ", t)
    res = {"archivo": ruta, "patrones": {}, "contexto_ambiguo": []}
    sin_persona = "--sin-persona" in sys.argv
    for k, p in PATRONES.items():
        if sin_persona and k in PATRONES_DE_ESTILO:
            continue
        hits = list(re.finditer(p, plano, re.I if k not in ("emoji",) else 0))
        res["patrones"][k] = len(hits)
        if k in ("segunda_persona", "primera_persona", "futuro"):
            for m in hits[:12]:
                res["contexto_ambiguo"].append(f"{k}: ...{plano[max(0, m.start()-60):m.end()+50].strip()}...")
    pies = [n for n in z.namelist() if re.match(r"word/footer\d*\.xml", n)]
    res["campo_PAGE_en_pie"] = any("PAGE" in z.read(n).decode("utf8") for n in pies)
    core = z.read("docProps/core.xml").decode("utf8") if "docProps/core.xml" in z.namelist() else ""
    res["metadatos_script"] = bool(re.search(r"python-docx|generated by", core, re.I))
    primeras = plano[:1200]
    res["portada_datos_minimos"] = {c: bool(re.search(p, primeras, re.I)) for c, p in ROTULOS_PORTADA.items()}
    res["revisor_presente"] = (revisor in plano) if revisor else None
    # Solo informativo: la bibliografía no se exige ni se reformatea; se revisa su calidad a mano
    res["referencias_detectadas"] = len(re.findall(r"(?m)^\s*\d+\.\s+[A-ZÁÉÍÓÚ][^\n]{0,80}\(\d{4}|\(s\. f\.\)", t))
    if "--json" in sys.argv:
        print(json.dumps(res, ensure_ascii=False, indent=2)); return 0
    print(f"== {ruta}")
    mal = {k: v for k, v in res["patrones"].items() if v}
    print("Patrones prohibidos:", mal if mal else "ninguno")
    for c in res["contexto_ambiguo"]:
        print("   ", c)
    print("Pie con campo PAGE:", res["campo_PAGE_en_pie"])
    print("Metadatos de script (python-docx):", "SÍ (corregir)" if res["metadatos_script"] else "no")
    faltan = [c for c, ok in res["portada_datos_minimos"].items() if not ok]
    print("Portada, datos mínimos:", "completos" if not faltan else f"FALTAN {faltan}")
    print("Revisor presente:", res["revisor_presente"])
    print("Referencias detectadas (informativo, no se exige):", res["referencias_detectadas"])
    print("\nLas coincidencias de persona/futuro se LEEN en contexto antes de reportar (\"usa\" en tercera persona es válido).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
